apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KalyaniAusekar/Shine-GitOps-Project.git
    targetRevision: main
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://kalyani-test-cluster-dns-13nks49z.hcp.canadacentral.azmk8s.io
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
